export const allCategories = [
    "Everything",
    "Work",
    "Personal",
    "Family",
    "Health",
    "Hobby",
    "Finance",
    "Personal Development",
    "Travel",
    "Career",
    "Social",
    "Home",
    "Writing",
  ];